### ISSUE TITLE
Error launching from MELD based on previously logged in EHR

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#25] opened 2021-12-21 16:23 UTC
@swmuir discovered the following error:
*Sean selected 3 EHRs to launch MyCarePlanner with; it didn't load. He closed out
*Attempted to relaunch from MELD but he gets the following error. Seems to not be able to "forget Cerner"

<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f9346befd7a74481fb5031b8e1f90875692ae3c/image.png" alt="image.png" />

Attempted to clear cache - didn't work.
Try clearing local storage.
Need to find new user-friendly way to resolve this.

**Comment by drdavec** [comment] 2022-05-16 19:58
Now managed as part of MVP definition.  Closing.

**Comment by kbertodatti** [comment] 2024-01-05 17:13
@swmuir found same bug on a different endpoint.

Reference #217.

**Comment by drbgfc** [comment] 2024-01-05 17:40
Attached is the log after the app loads the final time before the auth error[Console.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7131f833ac4121e75739780aa91eff5ab9f14ef/Console.txt)

**Comment by drbgfc** [comment] 2024-01-05 17:41
Here is a brief convo, responding to Sean about the issue as he wasn't seeing anything in local storage in Safari. I didn't review the log in depth, yet:

The local storage is there, there's plenty in it, according to the log
So, something to do with how you are viewing it, or how you can view it, is incorrect. I'm not sure the proper method in Safari
If you use chrome I can show you

Sean, 12:27 PM
thats the wonder of safari ;) 

12:28 PM
[Log] Key selected-endpoints-MCP exists in localForage (main.chunk.js, line 12201)
[Log] getSelectedEndpoints selectedEndpoints is truthy and length is > 0,Returning data:  – "[\"https://gw.interop.community/MCCDevelopment/data\",\"https://gw.interop.community/MCCTesting/data\",\"https://gw.interop.community/MCCStaging/…" (main.chunk.js, line 12248)
"[\"https://gw.interop.community/MCCDevelopment/data\",\"https://gw.interop.community/MCCTesting/data\",\"https://gw.interop.community/MCCStaging/data\"]"
[Log] isAnyEndpointNullOrUndefined selectedEndpoints.some(endpoint) : https://gw.interop.community/MCCDevelopment/data (main.chunk.js, line 971)
[Log] isAnyEndpointNullOrUndefined selectedEndpoints.some(endpoint) : https://gw.interop.community/MCCTesting/data (main.chunk.js, line 971)
[Log] isAnyEndpointNullOrUndefined selectedEndpoints.some(endpoint) : https://gw.interop.community/MCCStaging/data (main.chunk.js, line 971)
That's what it's loading (those 3)
Or, attempting to load

Sean, 12:29 PM
mystery solved - sort of - 

12:29 PM
Right, it doesn't mean it's not a bug
But can debug better now
Just need a clear way to reproduce, and the steps to do so
It appears that at some point, you tried to load those 3, though

Sean, 12:30 PM
yep

12:32 PM
Eventually it fails due to authorization on MCCDevelopment
Log] endpointInSavedData: – "https://gw.interop.community/MCCDevelopment/data" (main.chunk.js, line 12017)
[Log] fhirAccessDataWithMatchingServerUrl:  – undefined (main.chunk.js, line 11937)
[Log] if there is NO match, no need for further logic, return false, no authorization exists (main.chunk.js, line 11950)
[Log] This endpoint is NOT authorized (main.chunk.js, line 1060)
Personally, I don't think I've really tested with these URLs before (any of them)
dev, testing, staging
I think likely what's happening is, the local storage data thinks it's authorized, so it continues the logic, but fails when it hits the actual server, and is not handled gracefully (at all)
Why that happens, I'm not sure.  It could be related to the endpoints being so similar
I'll attach the log and add the comments
If you have time at some point to try to nail down an exact repro with steps, that would help. Eventually, I'll need to review a log of the full process, since, this is just after app return. There is a way to set up the browser to not delete the log when leaving to a different URL.
Thanks

**Closed** 2024-03-18 17:04 UTC
Labels: bug
