### ISSUE TITLE
MyCarePlanner caching unsuccessful login endpoint

### ISSUE THREAD

**Issue by MichelleBobo** [chronic-care/mcc-project#405] opened 2024-05-10 22:08 UTC
There is an issue with trying to access MyCarePlanner with external data multiple times in sequence. If you come back to it after a previous login, the app either fails with an error message, or it defaults to the login for the external site before it even properly loads the home page. On the user end, the issue can be fixed by clearing the browser cache, but that's not something that we want to be trying to talk our patients through. Is there a way to configure this so that it loads properly from scratch, every time?

**Comment by kbertodatti** [comment] 2024-05-14 15:20
Need to be clear on what is the expected behavior when you close it and reload within an hour of the first login.
Need to spend some time to reproduce. @drdavec to take first stab.

**Comment by mattStorer** [comment] 2024-05-17 22:23
I confirm this is a problem, I have experienced this myself.  Steps to reproduce:

1. log into MyCarePlanner via OHSU MyChart
2. connect to a third-party provider (e.g., Providence Oregon/Washington)
3. *DO NOT COMPLETE THE AUTHENTICATION PROCESS!*  Instead, repeat steps 1 and 2.
4. as soon as MyCarePlanner begins to load, control will redirect to the third-party provider's authentication endpoint selected in step 2.
5. The only way to resolve this is to wipe your browser's cache and data.

**Comment by kbertodatti** [comment] 2024-06-07 15:53
EMI to try logging in different EHRs using invalid password to see if the loop happens. @drdavec @savanahmueller @kbertodatti 

Document all failed paths.

**Comment by drbgfc** [comment] 2024-08-16 20:18
This comment is just a response to reading the comments above. Just some initial thoughts based on a loose memory of these inner workings. I will analyze and may come to a completely different conclusion:

Since we constantly leave the app for authorizaton and come back, we are constantly reloading it. Thus, each new load can't just wipe cached credentials as a solution. They are cached in order for multiple logins to work at the most basic level. What I'm hopeing we can do though, theoretically, is remove unsuccessful login attempts from local storage (or set them up in a way where they don't attempt to load with some sort of flag). But, the theory is based on identification. Because, that process can't really happen until we return to the app. When the app leaves, it assumes we are going to load x number of providers, when it returns, it attempts to load them (and this happens interatively for each), it's at that point that we know whether it was authorized or not, and if it wasn't it attempts to go do so. This is what creates the loop. We of course need to authorize if we are not. And in normal cases, it not being authorized is not an issue, it just means it timed out. So, it makes sense that it is attempting to authorize. Somehow, we have to identify the difference between a valid attempt to reauthorize and one that will create a loop due to an error authorizing. The 3rd party apps can't communicate with us (other than the tokens) and neither can we with them. Clearly, we need to reconsider how we handle authorization, and identify different scenarios and react somehow.

**Comment by drbgfc** [comment] 2024-08-16 20:27
Myabe, when the app returns, if we can't proceed because it's not authorized (which usually is a normal circumstance, as usually it's the first attempt to load a new provider), we don't just immediately try to reauthorize, somehow, right then and there, can we determine if it didn't authorize on purpose (user backed out mid-process on external SITE) or due to some error? Maybe not, BUT, the user can, right? So maybe, we have a dialog that asks the user if they want to attempt to reauthorize a specific provider, or skip it? This dialog would only appear for authorization requests. So would apply to multi-provider. However, it would cause an issue where the first time authorized, we'd have this question every time. Maybe that's not so bad? Anyway... I may be getting ahead of myself.

**Comment by drbgfc** [comment] 2024-08-31 03:43
Implemented with full screen dialog as mentioned above.

**Comment by drbgfc** [comment] 2024-08-31 03:46
Require user-input for unauthorized endpoints on app load
https://github.com/chronic-care/mycareplanner/commit/ab28f9ee14fb1ad6fcd30efcd52b88d6fc05da51

**Closed** 2024-09-16 19:35 UTC
Labels: bug, APP MyCarePlanner
