### ISSUE TITLE
Support display of Home loading Errors and handle no data on load/no launcher used on first load Error

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#277] opened 2023-05-03 12:44 UTC
List errors below the loading indications in red. Errors MAY or MAY NOT stop the loading and list a support contact message. 

Note: Also listed progress results if terminating, and added generic support email env.props and use it (will update later as per client)

**Comment by drbgfc** [comment] 2023-05-03 21:41
Dan Brown
  5:25 PM
@Dave Carlson
 
@Savanah Mueller
 what might be the most common errors that are encountered in testing. And, do we have it documented how to reproduce them? I want to ensure that a minimum I cover such cases





5:26
*in relation to loading data, that is


Dave Carlson
  5:30 PM
@Dan Brown
 I've encountered a few FHIR queries that return HTTP 403 (I believe, can check) when a specific provider install does not support a query parameter that we use, typically when that site has and older install, e.g. older version of Epic.  I'd like to follow a "best effort" approach to queries, e.g. if one query fails because they don't support a standard query paramter, we log/display the error but then proceed with the other queries.


Dan Brown
  5:34 PM
Good to know that we shouldn't halt the loading process in such cases - i'll add that comment to the ticket
Certainly interested in reproducable results. I think our biggest target though should be reporting errors to the user that have halted all progress so that they don't stare forever. This error would stop loading and display the error (and maybe suggest a support email)
However, in the example you described, where we can move along, I'm thinking we will provide the error in realtime, and maybe in the inline result of where the data would have been displayed as well (edited) 





New


Dave Carlson
  5:38 PM
Dan, I'll work up a test case where you could temporarily modify one of the queries in a way that should return an HTTP error, so you can test catching and displaying.  Some vendor FHIR endpoints are more forgiving in that they ignore unsupported parameters, but others just return a 403 if any parameters are provided that their endpoint does not support.

**Comment by drbgfc** [comment] 2023-05-04 00:01
Easiest failure to induce is trying to load the app for the first time w/o a launcher. So, I can start there.

**Comment by drbgfc** [comment] 2023-05-04 02:08
Another way to produce an error, 401: Let authentication expire and hit refresh manually and you will get a 20% load and the output in console of:
ProgressMessage: Reading patient data
fhirService.ts:235 Failure resolving FHIR.oath2.ready() promise in getFHIRData: HttpError: 401 Unauthorized
URL: https://fhir-myrecord.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12724070

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "expired",
            "diagnostics": "Bearer realm=\"fhir-myrecord.cerner.com\", error=\"invalid_token\", error_description=\"Token has expired\"",
            "expression": [
                "http.Authorization"
            ]
        }
    ]
}
Session expired! Please re-launch the app
App.tsx:77 Failure calling getFHIRData from App.tsx componentDidMount: HttpError: 401 Unauthorized
URL: https://fhir-myrecord.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12724070

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "expired",
            "diagnostics": "Bearer realm=\"fhir-myrecord.cerner.com\", error=\"invalid_token\", error_description=\"Token has expired\"",
            "expression": [
                "http.Authorization"
            ]
        }
    ]
}
Session expired! Please re-launch the app

**Comment by drbgfc** [comment] 2023-05-05 00:50
{/* Work in progress...implemented for use case application load w/o a launcher or existing prior connection*
            To reproduce, navigate directly to the app (from a new tab, not a refresh) w/o a launcher, e.g. http://localhost:8000/mycareplanner/index.html/ (replace domain/port as needed)}
            {/* TODO: Consider putting this in its own ErrorMessage component, adding CSS, and/or using MUI */}
            {/* TODO: Based on error type, if Terminating, remove CircularProgress from display, and maybe more progress indicators/messages
            (but, if removing more from the display, log that data to the Error Message (may need new fields), such as, percentage completed, progress status message, resources loaded) */}
            {/* Question: If the error is not terminating, should we even log it to the UI? Or if so, maybe it should have a more subtle appearance... */}

**Comment by drbgfc** [comment] 2023-05-05 00:54
Also need to add support for a vast array of situations produced from a variety of locations. This is extensive task so I'm thinking we limit to loading of initial data for now (connecting to client, and fhir resources) - basically, limit to Home, and not add much if not any new exceptions. That will take a lot of time and is a different task than display of such logic.

**Comment by drbgfc** [comment] 2023-05-10 00:01
Completed: Add provider link to error messages to provide an escape navigation, Remove CircularProgress from display as well as other progress indicators/irrelevant data if terminating error, log progress data to the output below Error message if terminating, Modularize/Externalize ErrorMessage into a functional component, Add terminators to imports, Reuse inline vars in env.props

To Do: 
1-Handle 401 authentication Error
2-Handle 403 connection Error
3-Identify and handle other errors

Suggestion:
-This ticket can become pretty infinite. Some logic is in place to handle things generally display-wise now, but of course logic can differ dramatically. I would sugges that we create separate tickets for the items in To Do above. For item 3, once identified, it would create more tickets as well. If agreed, we can move this ticket to 'Review' or 'Done'

**Closed** 2023-11-22 18:27 UTC
